-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 11:48:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Jooch-Skyfall
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Jooch-Skyfall` ;

-- -----------------------------------------------------
-- Schema Jooch-Skyfall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Jooch-Skyfall` DEFAULT CHARACTER SET utf8 ;
USE `Jooch-Skyfall` ;

-- -----------------------------------------------------
-- Table `Jooch-Skyfall`.`Jugadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jooch-Skyfall`.`Jugadores` ;

CREATE TABLE IF NOT EXISTS `Jooch-Skyfall`.`Jugadores` (
  `id_jugador` VARCHAR(7) NOT NULL COMMENT 'G###NA\n- G -> Generación: A-Z\n- ### -> identificador numerico\n- N -> inicial nombre\n- A -> inicial apellido',
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_jugador`),
  UNIQUE INDEX `id_jugadores_UNIQUE` (`id_jugador` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jooch-Skyfall`.`Contactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jooch-Skyfall`.`Contactos` ;

CREATE TABLE IF NOT EXISTS `Jooch-Skyfall`.`Contactos` (
  `id_contacto` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `Jugadores_id_jugadores` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id_contacto`, `Jugadores_id_jugadores`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  INDEX `fk_Contactos_Jugadores_idx` (`Jugadores_id_jugadores` ASC) VISIBLE,
  CONSTRAINT `fk_Contactos_Jugadores`
    FOREIGN KEY (`Jugadores_id_jugadores`)
    REFERENCES `Jooch-Skyfall`.`Jugadores` (`id_jugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jooch-Skyfall`.`Partidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jooch-Skyfall`.`Partidas` ;

CREATE TABLE IF NOT EXISTS `Jooch-Skyfall`.`Partidas` (
  `id_partida` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombre_partida` VARCHAR(45) NOT NULL,
  `dinero_total` DECIMAL(10,2) NOT NULL,
  `tipo_financiamiento` VARCHAR(45) NOT NULL,
  `tiempo_total` TIME NOT NULL,
  `puntos` INT NOT NULL,
  `Jugadores_id_jugadores` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id_partida`, `Jugadores_id_jugadores`),
  UNIQUE INDEX `id_partidas_UNIQUE` (`id_partida` ASC) VISIBLE,
  UNIQUE INDEX `nombre_partida_UNIQUE` (`nombre_partida` ASC) VISIBLE,
  INDEX `fk_Partidas_Jugadores1_idx` (`Jugadores_id_jugadores` ASC) VISIBLE,
  CONSTRAINT `fk_Partidas_Jugadores1`
    FOREIGN KEY (`Jugadores_id_jugadores`)
    REFERENCES `Jooch-Skyfall`.`Jugadores` (`id_jugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jooch-Skyfall`.`Cosechas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jooch-Skyfall`.`Cosechas` ;

CREATE TABLE IF NOT EXISTS `Jooch-Skyfall`.`Cosechas` (
  `id_cosecha` INT NOT NULL,
  `tomate` INT NOT NULL,
  `maiz` INT NOT NULL,
  `chile` INT NOT NULL,
  `cafe` INT NOT NULL,
  `aguacate` INT NULL,
  `total_cosechas` INT NOT NULL,
  PRIMARY KEY (`id_cosecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jooch-Skyfall`.`Trivias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jooch-Skyfall`.`Trivias` ;

CREATE TABLE IF NOT EXISTS `Jooch-Skyfall`.`Trivias` (
  `id_trivia` INT NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT NOT NULL,
  `resultado` TINYINT(1) NOT NULL COMMENT 'En MySQL, no existe un tipo de datos booleano nativo como en algunos otros sistemas de bases de datos. En cambio, MySQL utiliza el tipo de datos TINYINT(1) para representar valores booleanos.',
  PRIMARY KEY (`id_trivia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jooch-Skyfall`.`Selecciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jooch-Skyfall`.`Selecciones` ;

CREATE TABLE IF NOT EXISTS `Jooch-Skyfall`.`Selecciones` (
  `id_seleccion` INT NOT NULL,
  `id_carta` INT NOT NULL,
  `tipo` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_seleccion`),
  UNIQUE INDEX `id_seleccion_UNIQUE` (`id_seleccion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jooch-Skyfall`.`Ciclos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jooch-Skyfall`.`Ciclos` ;

CREATE TABLE IF NOT EXISTS `Jooch-Skyfall`.`Ciclos` (
  `id_ciclo` INT NOT NULL AUTO_INCREMENT,
  `no_ciclo` INT NOT NULL,
  `deuda` DECIMAL(10,2) NOT NULL,
  `tiempo` TIME NOT NULL,
  `interes` FLOAT NOT NULL,
  `dinero` DECIMAL(10,2) NOT NULL,
  `Partidas_id_partidas` INT ZEROFILL NOT NULL,
  `Partidas_Jugadores_id_jugadores` VARCHAR(7) NOT NULL,
  `Cosechas_id_cosecha` INT NOT NULL,
  `Trivias_id_trivia` INT NOT NULL,
  `Selecciones_id_seleccion` INT NOT NULL,
  PRIMARY KEY (`id_ciclo`, `Partidas_id_partidas`, `Partidas_Jugadores_id_jugadores`, `Cosechas_id_cosecha`, `Trivias_id_trivia`, `Selecciones_id_seleccion`),
  INDEX `fk_Ciclos_Partidas1_idx` (`Partidas_id_partidas` ASC, `Partidas_Jugadores_id_jugadores` ASC) VISIBLE,
  INDEX `fk_Ciclos_Cosechas1_idx` (`Cosechas_id_cosecha` ASC) VISIBLE,
  INDEX `fk_Ciclos_Trivias1_idx` (`Trivias_id_trivia` ASC) VISIBLE,
  INDEX `fk_Ciclos_Selecciones1_idx` (`Selecciones_id_seleccion` ASC) VISIBLE,
  CONSTRAINT `fk_Ciclos_Partidas1`
    FOREIGN KEY (`Partidas_id_partidas` , `Partidas_Jugadores_id_jugadores`)
    REFERENCES `Jooch-Skyfall`.`Partidas` (`id_partida` , `Jugadores_id_jugadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ciclos_Cosechas1`
    FOREIGN KEY (`Cosechas_id_cosecha`)
    REFERENCES `Jooch-Skyfall`.`Cosechas` (`id_cosecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ciclos_Trivias1`
    FOREIGN KEY (`Trivias_id_trivia`)
    REFERENCES `Jooch-Skyfall`.`Trivias` (`id_trivia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ciclos_Selecciones1`
    FOREIGN KEY (`Selecciones_id_seleccion`)
    REFERENCES `Jooch-Skyfall`.`Selecciones` (`id_seleccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
